version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.4.1

jobs: # ジョブの設定
  test:
    docker:
      - image: cimg/node:18.14.0
    parallelism: 2 # 並列数を2で実行
    steps:
      - checkout # Githubからソースコードをチェックアウトする
      - restore_cache:
          keys:
            - node-v1-{{ checksum "package-lock.json" }}
      - run:
          name: Install node packages # 依存関係のインストール
          command: npm install
      - save_cache:
          paths:
            - ./node_modules
          key: node-v1-{{ checksum "package-lock.json" }}
      - run:
          name: Run lint and format # lint and format
          command: npm run lint && npm run format
      - run:
          name: Run Test # UIとE2E以外のテストを実行
          command: |
            npm test -- --shard=$(($CIRCLE_NODE_INDEX+1))/$CIRCLE_NODE_TOTAL src/chapter2/getting_started_jest src/chapter2/assertion src/chapter2/06_group src/chapter2/07_mock
      - store_test_results: # テスト結果をアップロード
          path: reports/jest
      - store_artifacts: # カバレッジをアップロード
          path: reports/coverage
  ui-test:
    docker:
      - image: cimg/node:18.14.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-v2-{{ checksum "package-lock.json" }}
      - run:
          name: Install node packages
          command: npm install
      - save_cache:
          paths:
            - ./node_modules
          key: node-v2-{{ checksum "package-lock.json" }}
      - run:
          name: Run lint and format
          command: npm run lint && npm run format
      - run:
          name: Run UI Test
          command: npm test -- src/chapter2/ui
      - run:
          name: Upload Storybook to Chromatic
          command: npm run chromatic
  # 検証用のジョブになります。本書での説明はありません。
  e2e-test:
    docker:
      - image: cimg/node:18.14.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-v2-{{ checksum "package-lock.json" }}
      - run:
          name: Install node packages
          command: npm install
      - save_cache:
          paths:
            - ./node_modules
          key: node-v2-{{ checksum "package-lock.json" }}
      - run:
          name: apt update
          command: sudo apt update
      - browser-tools/install-chrome:
          chrome-version: "110.0.5481.77"
      - browser-tools/install-firefox:
          version: "109.0.1"
      - run:
          name: Run E2E Test
          command: npm test -- src/chapter2/e2e/puppeteer.test.ts src/chapter2/e2e/selenium.test.ts
  # 検証用のジョブになります。本書での説明はありません。
  playwright-test:
    docker:
      - image: mcr.microsoft.com/playwright:v1.30.0-focal
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-v2-{{ checksum "package-lock.json" }}
      - run:
          name: Install node packages
          command: npm install
      - save_cache:
          paths:
            - ./node_modules
          key: node-v2-{{ checksum "package-lock.json" }}
      - run:
          name: Run UI Test
          command: npm test -- src/chapter2/e2e/playwright.test.ts

workflows: # ワークフローの設定
  test:
    jobs:
      - test
      - ui-test
      # - e2e-test
      - playwright-test
